"""Task definitions for protocol methods."""

from .content_tasks import (
    GENERATE_BLOCK,
    GENERATE_BRANCHED_BLOCKS,
    GENERATE_CONDITIONAL_BLOCKS,
    GENERATE_LOOPED_BLOCKS,
    GENERATE_SEQUENTIAL_BLOCKS,
)
from .editorial_tasks import REFINE_CONTENT, REVIEW_CONTENT, VALIDATE_CONTENT

__all__ = [
    # Editorial tasks
    "REVIEW_CONTENT",
    "VALIDATE_CONTENT",
    "REFINE_CONTENT",
    # Content tasks
    "GENERATE_BLOCK",
    "GENERATE_SEQUENTIAL_BLOCKS",
    "GENERATE_LOOPED_BLOCKS",
    "GENERATE_BRANCHED_BLOCKS",
    "GENERATE_CONDITIONAL_BLOCKS",
]
