"""Reviewer agent for reviewing and improving generated content."""

import logging
from typing import Any, Dict

from ..models.agent_models import AgentRole, AgentStatus
from .base_agent import BaseAgent

logger = logging.getLogger(__name__)


class ReviewerAgent(BaseAgent):
    """Agent specialized in reviewing and improving content quality."""

    def __init__(self, agent_id: str = "reviewer_1", config: Dict[str, Any] | None = None):
        """Initialize the reviewer agent."""
        super().__init__(agent_id, AgentRole.REVIEWER, config)

    async def process_task(self, task_description: str, parameters: Dict[str, Any]) -> Dict[str, Any]:
        """
        Review and improve content generated by other agents.

        Args:
            task_description: Description of the review task
            parameters: Parameters including the content to review

        Returns:
            Dict containing the reviewed/improved content
        """
        await self.update_status(AgentStatus.WORKING)
        
        content = parameters.get("content", {})
        content_type = parameters.get("content_type")
        
        logger.info(f"Reviewing {content_type} content")
        
        # Perform review (in production, would use LLM for sophisticated review)
        reviewed_content = await self._review_content(content, content_type)
        
        await self.update_status(AgentStatus.COMPLETED)
        
        return reviewed_content

    async def _review_content(self, content: Dict[str, Any], content_type: str) -> Dict[str, Any]:
        """Review and potentially improve the content."""
        # Simple review logic - in production, would use LLM
        review_notes = {
            "reviewed": True,
            "quality_score": 8.5,
            "suggestions": [
                "Content structure is well-organized",
                "Engaging and interactive elements present",
                "Clear progression through material",
            ],
        }
        
        # Add review metadata to content
        if isinstance(content, dict):
            content["metadata"] = content.get("metadata", {})
            content["metadata"]["review"] = review_notes
        
        return content
